### ISSUE TITLE
Users API Documentation Mapping

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#13]
# Story
- As a developer,
- I should have clearly documented routes. request parameters, and responses to develop
- So that I can quickly develop and test these APIs

# Acceptance Criteria
- Markdown file per API Route that lists an example request object and example response object
- Must be in Markdown
- Must be per route (get-users.md, get-users-id.md)
- Example objects must be in JSON
-- example
```javascript
// GET /users RequestObject:
// none, just simple get
// ResponseObject
[{
  name: 'Professor',
  id: 'xxxxx-xxxx-xxxxxxx',
  //....
}]
```
- Must include of a list of high level use cases for each route
-- Example: /users is used when listing users of the application in the UI.
-- Example: /users/:id is used when showing a users individual profile in the UI

# Approach
- Think about all the use cases of our application, and where it will need to see or interact with user data. Create a list of use cases for the API, then propose routes based on those use cases.

**Comment by stephenthedev** [comment]
@bmanzella @angkimbrell1 Sprint 1

**Comment by bmanzella** [comment]
@raghunat Where should we submit our files?

**Comment by angkimbrell1** [comment]
@raghunat What should we call the files and about how many objects should there be?

**Comment by angkimbrell1** [comment]
@raghunat So we are to have separate markdown files for each API Route (get-users.md, get-users-id.md) and then also separate JSON files for each response object?

**Comment by stephenthedev** [comment]
@bmanzella @angkimbrell1 the path would be `docs/apis/users/<your files>`

The request/response objects would be directly in markdown, not a separate file:https://help.github.com/articles/creating-and-highlighting-code-blocks/
