### ISSUE TITLE
Spots API Documentation Mapping

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#14]
# Story
- As a developer,
- I should have clearly documented routes. request parameters, and responses to develop
- So that I can quickly develop and test these APIs

# Acceptance Criteria
- Markdown file per API Route that lists an example request object and example response object
- Must be in Markdown
- Must be per route (get-spots.md, get-spots-id.md)
- Example objects must be in JSON
-- example
```javascript
// GET /spots RequestObject:
// none, just simple get
// ResponseObject
[{
  name: 'Starbucks',
  id: 'xxxxx-xxxx-xxxxxxx',
  //....
}]
```
- Must include of a list of high level use cases for each route
-- Example: /users is used when listing users of the application in the UI.
-- Example: /users/:id is used when showing a users individual profile in the UI

# Approach
- Think about all the use cases of our application, and where it will need to see or interact with spot data. Create a list of use cases for the API, then propose routes based on those use cases.

**Comment by stephenthedev** [comment]
@hijcheung @KennedyAlex117 Sprint 1

**Comment by stephenthedev** [comment]
@hijcheung @KennedyAlex117 Missing submission

**Comment by KennedyAlex117** [comment]
When I try to push my dev files, I keep running into an error 403.

**Comment by stephenthedev** [comment]
OOO
