### ISSUE TITLE
User Interface Design

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#15]
# Story
- As a developer,
- I should have a wireframe of possible screens to develop against

# Acceptance Criteria
- Digital drawings submitted in a PR that reflect and label different screens for this application
- Should include all possible screens that you can conceive: Splash, Login, Profile, etc
- You can use any tool you want to create them, but the output submitted should be a png or jpeg

**Comment by stephenthedev** [comment]
@vincent12322 @alextadt @rouge888 @fahad221 @Dea-K  Sprint 1

**Comment by alextadt** [comment]
Do you want the files/images posted here or brought to class?

**Comment by alextadt** [comment]
Do each of us need to submit a copy if we work as a group?
Or would you rather us each create one individually for a variety of choices to pick from?

**Comment by stephenthedev** [comment]
@alextadt place your images in the repo at `docs/prototypes/<yourfiles>`

**Comment by stephenthedev** [comment]
@alextadt Each file should be in the following convention:

`<lastname>-<screenname>.<extension>`

**Comment by stephenthedev** [comment]
### MVP Screens After Discussion

1. Login
2. Sign up
3. Real Time Map
4. Create Spot
5. Check In
