### ISSUE TITLE
Data Definition

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#16]
# Story
- As a developer
- I should have a clear document stating the different models, and their fields for each data object in my application
- So that I can align and design a data store and the corresponding APIs

# Acceptance Criteria
- A data-definition.md file in a docs folder describing all models available
- Must include at least a User model and Spot model, but may include more
- All properties must have a corresponding datatype (ex name:String)
- All properties must user camelCase

**Comment by stephenthedev** [comment]
@KenjiShiguma @dreagle95 Sprint 1

**Comment by dreagle95** [comment]
when trying to checkout a new branch, the command prompt is telling me that -v is an unknown switch. 
Did you mean -b?

**Comment by stephenthedev** [comment]
@dreagle95 It is -b, did I write -v somewhere?

**Comment by dreagle95** [comment]
I just checked it and it says -b, I could have sworn it said -v. Sorry about that

**Comment by KenjiShiguma** [comment]
Most of dreagle95's Markdown, but in UML and with some additional variables: 

![uml data definitions](https://cloud.githubusercontent.com/assets/9452318/23520207/fb0d799e-ff47-11e6-96ce-1b15c613dfba.png)

**Comment by stephenthedev** [comment]
### Data models for MVP

|User|
|email|
|password|

|Spot|
|id: UUID|
|location: float[float[]]| // lat,long pairs
|name: String|
|checkIns: String[]|

**Comment by dreagle95** [comment]
@raghunat I've been trying to push the updated file and it says that everything was successful as far as pushing it however I don't see it as a pull request in github. Do you see anything on your end?

**Comment by stephenthedev** [comment]
https://github.com/raghunat/hotspot/pull/24
https://github.com/raghunat/hotspot/pull/24
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=link-preview

https://github.com/raghunat/hotspot/pull/24

https://github.com/raghunat/hotspot/pull/24

Stephen Raghunath

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Mon, Mar 06, 2017 at 2:13 PM dreagle95

<
mailto:dreagle95 <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/raghunat
I've been trying to push the updated file and it says that everything was successful as far as pushing it however I don't see it as a pull request in github. Do you see anything on your end?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/raghunat/hotspot/issues/16#issuecomment-284500513
, or

**Comment by stephenthedev** [comment]
@dreagle95 @KenjiShiguma Did we get this finished?

**Comment by dreagle95** [comment]
I thought it was finished and uploaded.  I'm trying to find the issue right now

**Comment by dreagle95** [comment]
@raghunat i checked #24 and that is the updated version.  I'm not sure why it won't put a newline between each line because in my file there is a newline
