### ISSUE TITLE
Base UI Project

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#18]
# Story
- As a developer
- I should have a modern interface built in a modern interface framework with a solid toolchain so that I can iterate quickly on UI needs

# Acceptance Criteria
- a `ui/` folder at the root
- with an angular 2 project inside
- built from @angular/cli

**Comment by stephenthedev** [comment]
@siragusamatt

**Comment by siragusamatt** [comment]
How do I create an angular project? Also, what does the project have to contain?

**Comment by stephenthedev** [comment]
1. `npm install -g @angular/cli`
2. `mkdir ui` // in the repo
3. `ng new hotspot-ui`
4. Finished

**Comment by siragusamatt** [comment]
#28 Issue 18

**Comment by stephenthedev** [comment]
@battlebite
