### ISSUE TITLE
API Get Spots

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#37]
# API Request
## Story
- As a developer
- I need an API route to retrieve many spot information
- So that I can show a list of spots

## Acceptance Criteria
- Route `/spots`
- Method: GET
- Request Object: ~
- Response
 
```javascript
[{
	definition from PR #16
}, {
	definition from PR #16
}, {
	definition from PR #16
}]
```

- written in a `spots-api/api/get-spots.js` file 
- Include an `spots-api/api/post-spots.spec.js` file with a `supertest` for the new endpoint 

## Approach
- Since we have no database yet, just send back example data.

**Comment by stephenthedev** [comment]
@dreagle95 Sprint 2

**Comment by dreagle95** [comment]
I shouldn't try and install the modules such as supertest to this correct?

**Comment by dreagle95** [comment]
Isn't it npm test to test with supertest?

**Comment by dreagle95** [comment]
Ignore that question, but I have a more important one.  How would one go about checking if a json is equal.  It wouldn't be res.text.should.equal.  I've tried replacing text with the objects name, body and a couple other things I found online to no avail. Am I going about it wrong?

**Comment by stephenthedev** [comment]
Completed
