### ISSUE TITLE
API Create Spot

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#39]
# API Request
## Story
- As a developer
- I need an API route to create a spot
- So that I can create spots

## Acceptance Criteria
- Route `/spots`
- Method: POST
- Request Object:

```javascript
{
	definition from PR #16
}
```

- Response
 
```javascript
{
	definition from PR #16 // send back the request body for now
}
```

- written in a `spots-api/api/post-spots.js` file 
- Include an `spots-api/api/post-spots.spec.js` file with a `supertest` for the new endpoint 

## Approach
- Since we have no database yet, just send back example data.

**Comment by stephenthedev** [comment]
@siragusamatt Sprint 2

**Comment by siragusamatt** [comment]
Do I need to create a separate 'Spots' file and use that as the route? I'm unsure on how to use the /spots route. Also, I'm unsure what I'd be requesting if all I'm doing is creating a spot.

**Comment by stephenthedev** [comment]
Completed
