### ISSUE TITLE
Gateway API Login

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#40]
# API Request
## Story
- As a developer
- I need an API route to log a user in
- So that I can validate who is a user from the UI

## Acceptance Criteria
- Route `/login`
- Method: POST
- Request Object:

```javascript
{
	"email": "string",
        "password": "string"
}
```

- Response
 
```javascript
{
	definition from PR #16 // user object
}
```

- written in a `gatewat-api/api/login.js` file 
- Include an `gateway-api/api/login.spec.js` file with a `supertest` for the new endpoint 

## Approach
- Since we have no database yet, just send back example data.

**Comment by stephenthedev** [comment]
@rouge888 Sprint 2

**Comment by stephenthedev** [comment]
@rouge888 Up

**Comment by rouge888** [comment]
#62
