### ISSUE TITLE
API Delete User

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#42]
# API Request
## Story
- As a developer
- I need an API route to delete an individual user's information
- So that I can remove it's individual information

## Acceptance Criteria
- Route `/users/:id`
- Method: DELETE
- Request Object: ~
- Response
 
```javascript
{
	status: 'deleted'
}
```

- written in a `users-api/api/delete-user.js` file 
- Include an `users-api/api/delete-user.spec.js` file with a `supertest` for the new endpoint 

## Approach
- Since we have no database yet, just send back example data.

**Comment by stephenthedev** [comment]
@KenjiShiguma Sprint 2

**Comment by KenjiShiguma** [comment]
@raghunat Hi, I wanted to know if I can talk to you for around 5 minutes, class unrelated.

**Comment by stephenthedev** [comment]
Please email me directly, and of course.

Stephen Raghunath

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Sat, Mar 04, 2017 at 11:55 AM Kermit Mitchell III

<
mailto:Kermit Mitchell III <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/raghunat
Hi, I wanted to know if I can talk to you for around 5 minutes, class unrelated.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/raghunat/hotspot/issues/42#issuecomment-284164383
, or

**Comment by stephenthedev** [comment]
@KenjiShiguma  Up

**Comment by stephenthedev** [comment]
@KenjiShiguma up

**Comment by KenjiShiguma** [comment]
@raghunat I have no idea what any of this means anymore to be honest. Is there another issue I can look at for reference?

**Comment by KenjiShiguma** [comment]
How do I upload my answer? @raghunat

**Comment by KenjiShiguma** [comment]
@raghunat 

// delete-users.js

module.exports = function () {
  return function (req, res) {
    res.send('USER DELETED!');
  }
}

**Comment by KenjiShiguma** [comment]
@raghunat 

// delete-useers.spec.js

// supertest
const app = require('../app.js');
const should = require('should');
const supertest = require('supertest');


describe('DELETE /users/:id', () => {

  it('SHOULD DELETE A USER!', done => {
    supertest(app)
    .delete('/users/666')
    .end((err, res) => {
      res.text.should.equal('USER DELETED!');
      done();
    });
  });
});

**Comment by KenjiShiguma** [comment]
@raghunat I cloned the repo and did some extra work as well, but now it won't let me pull up to the master; how do I do it? O_o
