### ISSUE TITLE
Set up Mongo Lab

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#43]
# Data Store
## Story
- As a developer
- I need a scalable datastore for storing users and spots

## Acceptance Criteria
- Create a "hotspot" gmail account (do not embed the password anywhere in code!)
- Follow http://learnwebtutorials.com/mongodb-tutorial-getting-started-mongolab with that email account (free tier)
    - The tutorial has you test your new db from the terminal. Please do those steps, and take a screenshot of it, and paste it here, then email me the creds for everything
- Paste in a ticket comment listing an object from your terminal
- Email only the professor the credentials for the gmail account, and the mongo lab credentials at this time.

**Comment by stephenthedev** [comment]
@Dea-K  Sprint 2

**Comment by Deakyu** [comment]
Hi, I created hotspot gmail account and mongo lab account, and also dbuser for the database.
But I don't understand what a ticket comment is, and also what object you are referring to is.
Can you elaborate that?

**Comment by stephenthedev** [comment]
@Dea-K The tutorial has you test your new db from the terminal. Please do those steps, and take a screenshot of it, and paste it here, then email me the creds for everything

**Comment by Deakyu** [comment]
![db_object](https://cloud.githubusercontent.com/assets/17103091/23590714/1fe6d324-01b3-11e7-9c62-0b8aa20f6e4b.png)

**Comment by stephenthedev** [comment]
Completed
