### ISSUE TITLE
DELETE /users/:id

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#67]
# DELETE /users/:id 

## Story

- As a developer
- I want an api that delete a single user
- so that I can remove a user

## Acceptance Criteria

- Update the DELETE /users/:id api use a mongo collection called 'users'
- For the find query object, use `{_id: req.params.id}`
- your response line should be something like `res.json('User deleted');`
- Update your test to pass under with the new mongo connection

## Approach

- Use the API listed here: 
	- http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html
	- http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html

**Comment by stephenthedev** [comment]
@KenjiShiguma Sprint due TUESDAY 3/28

**Comment by stephenthedev** [comment]
@KenjiShiguma up

**Comment by KenjiShiguma** [comment]
@raghunat As you said before, this is very similar to issue #42 except with an actual MongoDB attached. I really need help with this.
