### ISSUE TITLE
GET /spots

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#68]
# GET /spots 

## Story

- As a developer
- I want an api that lists spot information
- so that I can query a list of spots

## Acceptance Criteria

- Update the GET /spots api do use a mongo collection called 'spots'
- For the find query object, use `{}`
- Update your test to only make the following assertion

```js
res.body.should.be.an.Array
```

## Approach

- Use the API listed here: 
	- http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html
	- http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html

**Comment by stephenthedev** [comment]
@dreagle95 Sprint due Tuesday 3/28

**Comment by dreagle95** [comment]
Will you be sending the .env file with the username and password for testing purposes?

**Comment by stephenthedev** [comment]
Up
