### ISSUE TITLE
POST /spots

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#69]
# POST /spots

## Story

- As a developer
- I want an api that creates a single spot
- so that I can add a spot

## Acceptance Criteria

- Update the POST /spots api use a mongo collection called 'spots'
- To create, use something like `.insert(req.body)`
- your response line should be something like `res.json(result);`
- Update your test to pass under with the new mongo connection

## Approach

- Use the API listed here: 
	- http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html
	- http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html

**Comment by stephenthedev** [comment]
@siragusamatt Sprint due Tuesday 3/28

**Comment by siragusamatt** [comment]
What was the method that we used to connect to the database without using the username and password directly in the code?

**Comment by stephenthedev** [comment]
@siragusamatt Look at the alive route. You actually don't need to do anything, it is setup for you
