### ISSUE TITLE
Gateway Nearby Spots

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#84]
# In Gateway API
## Acceptance Criteria
- New  GET /nearby-spots?lat=x&long=x api route
	- GET /spots then loop through, and check bounds

On success returns `[SpotObjects]`

## Approach
- Use superagent within the gateway API to create ReST API calls to the other API

**Comment by stephenthedev** [comment]
@dreagle95 @siragusamatt  Sprint due 4/11

**Comment by siragusamatt** [comment]
Are the latitude and longitude representing a single spot or the users current position? How do we come up with the bounds that we're checking the spot against? @raghunat
