### ISSUE TITLE
Gateway API my-profile

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#85]
# In Gateway API
## Acceptance Criteria
-  GET /my-profile/:id
	- GET /users/:id -> removes password from response 

On success returns `{UserObjectWithoutPasswordField}`

## Approach
- Use superagent within the gateway API to create ReST API calls to the other API

**Comment by stephenthedev** [comment]
@angkimbrell1 @fahad221  Sprint due 4/11

**Comment by angkimbrell1** [comment]
@raghunat What should the file be called?

**Comment by stephenthedev** [comment]
@angkimbrell1 `gateway-api/api/get-my-profile.js` and `gateway-api/api/get-my-profile.spec.js`
