### ISSUE TITLE
Gateway API check-in

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#86]
# In Gateway API
## Acceptance Criteria
- POST /check-in/:spot_id with the users email in the post body
	- Sends PUT /spots/:id -> email of the users

On success returns `{SpotObject}`

## Approach
- Use superagent within the gateway API to create ReST API calls to the other API

**Comment by stephenthedev** [comment]
@KenjiShiguma @bmanzella  Sprint due 4/11

**Comment by KenjiShiguma** [comment]
I'll submit all 4 at once

**Comment by KenjiShiguma** [comment]
@bmanzella @raghunat So is #91 similar to what we must do here?
