### ISSUE TITLE
Gateway API new-user

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#88]
# In Gateway API
## Acceptance Criteria
POST /new-user -> with email and password

On success returns `{SpotObject}`

## Approach
- Use superagent within the gateway API to create ReST API calls to the other API

**Comment by stephenthedev** [comment]
@rouge888 @vincent12322 Sprint due 4/11

**Comment by rouge888** [comment]
#94

**Comment by rouge888** [comment]
#94
